[package]
name = "babili"
version = "0.1.0"
authors = ["Yuan He <lendage@gmail.com>"]

[dependencies]
http-muncher = "0.2.0"
rustc-serialize = "0.3.15"
sha1 = "0.1.1"
byteorder = "0.5"
mio = { git = "https://github.com/carllerche/mio" }
